services:
  gladius-csharp:
    build: ./CSharp

  serpens-python:
    build: ./Python

  celeritas-go:
    build: ./Go

  # scutum-rust:
  #   build: ./Rust

  senex-java:
    build: ./Java

  spiritus-javascript:
    build: ./JavaScript

  antiquus-php:
    build: ./PHP

  # pulcher-swift:
  #   build: ./Swift

  novus-kotlin:
    build: ./Kotlin

  famulus-bash:
    build: ./Bash
