services:
  gladius-csharp:
    build: ./CSharp
    container_name: codex-gladius

  serpens-python:
    build: ./Python
    container_name: codex-serpens

  celeritas-go:
    build: ./Go
    container_name: codex-celeritas

  scutum-rust:
    build: ./Rust  
    container_name: codex-scutum
