services:
  gladius-csharp:
    build: ./CSharp
    container_name: codex-gladius

  serpens-python:
    build: ./Python
    container_name: codex-serpens

  celeritas-go:
    build: ./Go
    container_name: codex-celeritas

  # Временно отключаем проблемные
  # scutum-rust:
  #   build: ./Rust
  #   container_name: codex-scutum

  # senex-java:
  #   build: ./Java
  #   container_name: codex-senex

  spiritus-javascript:
    build: ./JavaScript
    container_name: codex-spiritus

  antiquus-php:
    build: ./PHP
    container_name: codex-antiquus

  # pulcher-swift:
  #   build: ./Swift
  #   container_name: codex-pulcher

  # novus-kotlin:
  #   build: ./Kotlin
  #   container_name: codex-novus

  famulus-bash:
    build: ./Bash
    container_name: codex-famulus
